package com.priceorbit.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;

import java.util.ArrayList;
import java.util.List;

// ✅ @Document tells Spring Boot this class maps to a MongoDB collection called "users"
@Document(collection = "users")
// ✅ @Data from Lombok automatically generates getters, setters, equals, hashCode, toString
@Data
// ✅ Generates a constructor with NO arguments (required by MongoDB)
@NoArgsConstructor
// ✅ Generates a constructor with ALL arguments (useful for creating users in code)
@AllArgsConstructor
public class User {

    // ✅ @Id marks this as the MongoDB document ID (auto-generated by MongoDB)
    @Id
    private String id;

    // ✅ The user's display name (e.g. "Mohamed")
    private String name;

    // ✅ @Indexed(unique = true) means no two users can have the same email
    // MongoDB will reject duplicate emails automatically
    @Indexed(unique = true)
    private String email;

    // ✅ This will store the BCrypt-hashed password — NEVER the plain text password
    private String password;

    // ✅ List of product IDs the user has saved (matches Product's id field)
    // Initialized as empty list so it's never null
    private List<String> savedProducts = new ArrayList<>();
}